---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: AWX_NAMESPACE
spec:
  # AWX user
  admin_user: super
  #admin_password_secret: awx-admin-password
  #admin_email: youremail@example.com

  # ingress
  ingress_type: ingress
  hostname: AWX_SUBDOMAIN.DOMAIN
  ingress_annotations: |
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: awx-service
    cert-manager.io/cluster-issuer: CERT_ISSUER
  ingress_path: /
  ingress_tls_secret: tls-DOMAIN-awx

  # postgres
  postgres_storage_class: local-storage
  #postgres_configuration_secret: awx-prod-postgres-configuration

  # projects
  projects_persistence: true
  projects_storage_class: local-storage
  projects_storage_access_mode: ReadWriteOnce

  # Uncomment to reveal "censored" logs
  no_log: false
  auto_upgrade: true
