---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-tcp-services
  namespace: squid
data:
  3128: "squid/squid-service:3128"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squid-volume-claim
  namespace: squid
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: squid-service
  namespace: squid
  labels:
    app: squid
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: squid-port
    port: 3128
    targetPort: 3128
    protocol: TCP
#    nodePort: 3128
  selector:
    app: squid
#  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  namespace: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: ubuntu/squid:latest
        ports:
        - containerPort: 3128
          name: squid
          protocol: TCP
        volumeMounts:
        - name: squid-config-volume
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
        - name: squid-data
          mountPath: /var/spool/squid
      volumes:
        - name: squid-config-volume
          configMap:
            name: squid-config
            items:
            - key: squid
              path: squid.conf
        - name: squid-data
          persistentVolumeClaim:
            claimName: squid-volume-claim
