---
apiVersion: v1
kind: Service
metadata:
  name: ntp-server
  namespace: ntp
  labels:
    service: ntp-server
spec:
  ports:
    - name: "123"
      port: 123
      protocol: UDP
      targetPort: 123
  selector:
    service: ntp-server
  type: LoadBalancer
